name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tfx-cli
        run: npm install -g tfx-cli

      - name: Package
        run: make package

      - name: Create Draft Release
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          title: Release ${{ github.ref_name }}
          files: ./*.vsix
