name: Build and Release

on:
  push:
    branches-ignore:
      - '*'
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install tfx-cli
        run: npm install -g tfx-cli

      - name: Build project
        run: make build

      - name: Upload .vsix file
        uses: actions/upload-artifact@v2
        with:
          name: vsix-artifact
          path: ./*.vsix