name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tfx-cli
        run: npm install -g tfx-cli

      - name: Build
        run: make build

      - name: Tests
        run: make test

